### ISSUE TITLE
Action claims that the dist/index.js file doesn't exist?

### ISSUE THREAD

**Issue by lee-dohm** [JasonEtco/build-and-tag-action#4]
When I run `npm ci && npm run build` locally on the latest code in my repo, the `dist/index.js` file is created. So I'm not sure why I'm getting [this error](https://github.com/lee-dohm/close-matching-issues/runs/681649609?check_suite_focus=true#step:3:9)?

Thoughts?

**Comment by JasonEtco** [comment]
Hm, thanks for opening, and for trying it out @lee-dohm. Everything looks correct to me 🤔 I'm guessing that the setup script wasn't run, otherwise we'd see the log output. It should have run though; I added some more logs in cba59090bd17019871df1fd9fc5771c340a4d9d4 so we should at least see what it's doing with the setup script. Are you able to try again?

**Comment by JasonEtco** [comment]
Saw that you re-ran it @lee-dohm, thanks 🙏 So:

![image](https://user-images.githubusercontent.com/10660468/82132143-8df37a80-97aa-11ea-8b6c-8f019f379923.png)

It looks like `@actions/exec` doesn't map super well for commands with `&&`. I didn't catch it in this repo, because I have to build it in the workflow instead of in the action itself (so I set `setup: ''`). I'm not sure how to solve this 😞 Might be worth removing the setup script entirely, rather than have something that only works sometimes.

**Comment by lee-dohm** [comment]
Hmmm ... let me try changing to using `run` steps instead of relying on the setup script and see if that works 🤔

**Comment by lee-dohm** [comment]
Yep, that worked 👍 Want me to leave this open for you to track the problem?

**Comment by JasonEtco** [comment]
Yes please, thanks @lee-dohm!! I'm going to first see if there's a "right way" to do multiple commands, might need a change to `@actions/exec`. If that doesn't pan out, I'll remove the setup script entirely.

**Comment by lee-dohm** [comment]
Thank you for building this so I don't have to 😆
